version: "3.9"
services:
  web:
    image: docker.io/bitnami/laravel:9
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    image: mysql
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-e", "SELECT 1"]
      interval: 10s
    environment:
      MYSQL_USER: web
      MYSQL_PASSWORD: web
      MYSQL_DATABASE: lanadmin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 3306
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
    environment:
      REDIS_PASSWORD: redis
    expose:
      - 6379
volumes:
  database: